defaults:
  - timer_health_check_settings@pi_deployment_node.timer_health_check_settings: default
  - subscriber_health_check_settings@pi_deployment_node.subscriber_health_check_settings: default

pi_deployment_node:
  _target_: openpi.deploy.openpi_franka.PiDemoDeploymentNode
  dt_policy: 0.1  # seconds between policy evaluations
  dt_plan: 1.3  # seconds between policy planning
  zed_settings:
    serial_number: ???
    buffer_len: 60
    device: "cpu"
    resolution: "vga"
    fps: 60
  oak_settings:
    serial_number: ???
    buffer_len: 60
    resolution: "vga"
    fps: 60
  fr3_buffer_len: 100
  history_len: 2  # (history_len - 1) * dt_policy seconds of history
  name: "pi_deployment_node"
  domain_id: ???
  auto_start: true
  timer_health_check_settings:
    active: false
  subscriber_health_check_settings:
    active: false


